# playbook is a list of plays
- name: PLAY-1
  hosts: localhost
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-1 TASK"

- name: PLAY-2
  hosts: localhost
  tasks:
  - name: PLAY 2 TASK
    ansible.builtin.debug:
      msg: "Hello from PLAY 2 TASK"