#Play level variables
- name: variables from PLAY level1
  hosts: localhost
  vars:
    course: "DevOps"
    Trainer: "sivakumar"
    Duration: "110 hrs"
  tasks:
  - name: check variable from play level
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"