#Task level variables
- name: variables from PLAY level1
  hosts: localhost
  vars:
    course: "DevOps in play level"
    Trainer: "sivakumar"
    Duration: "110 hrs"
  tasks:
  - name: check variable
    vars: # If any variable is available in Play and task with same variable name it will consider task level 
      course: "DevOps with AWS in task level"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"