- name: variables from PLAY level1
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variable from file
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"