- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install some packages and uninstall some packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}" # item is a default key word
    loop:
    - {name: 'git', state: 'present'} #item
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'nginx', state: 'present'}